name: "Glassmorphism"
description: "Modern glassmorphic design with frosted glass cards, deep purple gradient background, and floating decorative elements. Features backdrop blur effects and glowing priority indicators."
version: "1.0.0"
author: "Newsloom"
theme: "dark"
features:
  - "Deep purple gradient background (linear-gradient 135deg)"
  - "Frosted glass cards with backdrop-filter: blur(16px)"
  - "Floating decorative blobs with blur effects"
  - "Gradient text (purple → cyan)"
  - "Glowing priority dots with box-shadow"
  - "Smooth rounded corners (border-radius: 16px)"
  - "Pill-shaped glass badges"
  - "Modern glassmorphic aesthetic"
