name: "Education Warm"
description: "Friendly, textbook-inspired design with warm white background and educational palette. Features gentle orange accents, rounded corners, and enhanced readability for teaching environments."
version: "1.0.0"
author: "Newsloom"
theme: "light"
features:
  - "Warm white background (#FFFDF7) for reduced eye strain"
  - "Warm orange (#FF6B35) primary with calming blue (#4A90D9) secondary"
  - "Friendly rounded corners and spacious layout"
  - "Education-optimized typography and spacing"
  - "Textbook-style section headers with icons"
  - "Color-coded priority system with soft indicators"
  - "Optimized for classroom projection and printing"
  - "Academic paper-style executive summary box"