name: "Deep Space Terminal"
description: "Bloomberg Terminal meets deep space aesthetics with electric cyan accents, grid patterns, and scanline effects. Ultra-dense data layout with monospace terminal feel."
version: "1.0.0"
author: "Newsloom"
theme: "dark"
features:
  - "Terminal-inspired monospace typography"
  - "CSS grid pattern overlay"
  - "Scanline visual effect"
  - "Electric cyan (#00D4FF) accent color"
  - "Data-dense compact card layout"
  - "Left border priority indicators"
  - "Dark background (#020617) optimized for PDF"
  - "Cyberpunk aesthetic with violet secondary colors"
