name: "Art Deco"
description: "1920s Art Deco inspired template with geometric patterns and golden age luxury aesthetics"
version: "1.0.0"
author: "Newsloom Template Factory"
theme: "dark"
features:
  - "Deep navy #1A1A2E background"
  - "Gold accent #D4AF37"
  - "Geometric border patterns"
  - "Fan and sunburst decorations"
  - "Gatsby era luxury feel"
  - "Jazz age sophistication"