name: "Swiss Grid"
description: "Strict Swiss International Typographic Style with mathematical grid system and minimal color palette. Features precise typography, extensive white space, and rational design principles."
version: "1.0.0"
author: "Newsloom"
theme: "light"
features:
  - "Pure white background (#FFFFFF) for maximum clarity"
  - "Red (#FF0000) as single accent color for maximum impact"
  - "Helvetica-based typography with perfect mathematical spacing"
  - "Strict modular grid system with precise alignment"
  - "Extensive negative space for visual breathing room"
  - "Rational, objective design with no decorative elements"
  - "Swiss-style asymmetrical layout composition"
  - "Modernist typographic hierarchy and spacing"