name: "Strategy Plus"
description: "Strategy& (PwC) inspired template with red and orange accent colors and executive brief aesthetics"
version: "1.0.0"
author: "Newsloom Template Factory"
theme: "light"
features:
  - "PwC red #C41230 with orange #D04A02"
  - "Extreme minimalism design"
  - "Generous white space"
  - "Fine line decorations"
  - "Executive brief format"
  - "Modern corporate elegance"