name: "Oxford Navy"
description: "Classic British academic design inspired by Oxford University. Warm off-white background with deep navy blue accents, refined serif typography for scholarly distinction."
version: "1.0.0"
author: "Newsloom Templates"
theme: "light"
features:
  - "Oxford Blue (#002147) primary color"
  - "Warm off-white (#FFFFF8) background"
  - "Classic British academic styling"
  - "Fine serif typography for elegance"
  - "Traditional Oxford aesthetic"
  - "PDF/print optimized"
  - "CJK font support"
  - "Priority indicators (🔴/🟡/🟢)"