name: "Government Official"
description: "Serious, formal government document style with official color scheme and structured layout. Features document numbering, formal headers, and institutional typography for official communications."
version: "1.0.0"
author: "Newsloom"
theme: "light"
features:
  - "Clean white background (#FFFFFF) for official documents"
  - "Deep navy blue (#003366) primary with dark red (#8B0000) accents"
  - "Formal document numbering and classification headers"
  - "Institutional serif typography for authority"
  - "Structured table-like brief layout"
  - "Official seal-inspired section dividers"
  - "Print-optimized for formal distribution"
  - "Government-style priority classification system"