"""Layer 4: Report generation (Markdown, HTML, Cards, RSS)"""

import json
from pathlib import Path
from datetime import datetime
from typing import Dict, List
from jinja2 import Template


class ReportGenerator:
    """Multi-format report generator"""

    def __init__(self, config: dict):
        self.config = config
        self.formats = config.get('generate', {}).get('formats', ['markdown', 'html'])
        self.generate_rss = config.get('generate', {}).get('generate_rss', False)

    def generate_markdown(self, items: List, date_str: str, output_path: Path):
        """
        Generate Markdown report
        From morning-brief summary.py
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Group by channel
        by_channel = {}
        for item in items:
            channel = getattr(item, 'channel', 'general')
            by_channel.setdefault(channel, []).append(item)

        # Sort items by score within each channel
        for channel in by_channel:
            by_channel[channel].sort(key=lambda x: getattr(x, 'score', 0), reverse=True)

        # Generate markdown
        lines = [
            f"# Daily Report - {date_str}",
            "",
            f"*Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
            "",
            "---",
            ""
        ]

        # Table of contents
        lines.append("## Table of Contents")
        lines.append("")
        for channel in sorted(by_channel.keys()):
            channel_name = channel.replace('_', ' ').title()
            lines.append(f"- [{channel_name}](#{channel.lower()})")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Content sections
        for channel in sorted(by_channel.keys()):
            items_list = by_channel[channel]
            channel_name = channel.replace('_', ' ').title()

            lines.append(f"## {channel_name}")
            lines.append("")
            lines.append(f"*{len(items_list)} items*")
            lines.append("")

            for i, item in enumerate(items_list, 1):
                # Get attributes safely
                title = getattr(item, 'title', 'No title')
                url = getattr(item, 'url', '#')
                author = getattr(item, 'author', 'Unknown')
                source = getattr(item, 'source', 'unknown')
                score = getattr(item, 'score', 0)

                lines.append(f"### {i}. [{title}]({url})")
                lines.append("")
                lines.append(f"**Source:** {source} | **Author:** {author} | **Score:** {score:.1f}")
                lines.append("")

                # Add text preview
                text = getattr(item, 'text', '')
                if text:
                    preview = text[:300] + "..." if len(text) > 300 else text
                    lines.append(f"> {preview}")
                    lines.append("")

                lines.append("---")
                lines.append("")

        # Footer
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Newsloom 📰*")

        # Write file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

        print(f"📄 Generated Markdown: {output_path}")

    def generate_html(self, items: List, date_str: str, output_path: Path):
        """
        Generate HTML report with dark/light theme
        From twitter-watchdog template
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # Group by channel
        by_channel = {}
        for item in items:
            channel = getattr(item, 'channel', 'general')
            by_channel.setdefault(channel, []).append(item)

        # Sort items
        for channel in by_channel:
            by_channel[channel].sort(key=lambda x: getattr(x, 'score', 0), reverse=True)

        # HTML template
        html_template = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Report - {{ date_str }}</title>
    <style>
        :root {
            --bg-primary: #ffffff;
            --bg-secondary: #f5f5f5;
            --text-primary: #333333;
            --text-secondary: #666666;
            --border-color: #e0e0e0;
            --link-color: #0066cc;
            --card-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        [data-theme="dark"] {
            --bg-primary: #1a1a1a;
            --bg-secondary: #2d2d2d;
            --text-primary: #e0e0e0;
            --text-secondary: #a0a0a0;
            --border-color: #404040;
            --link-color: #66b3ff;
            --card-shadow: 0 2px 8px rgba(0,0,0,0.5);
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
            line-height: 1.6;
            background-color: var(--bg-secondary);
            color: var(--text-primary);
            transition: background-color 0.3s, color 0.3s;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background-color: var(--bg-primary);
            padding: 30px 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            box-shadow: var(--card-shadow);
        }

        h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            background-color: var(--bg-primary);
            border: 1px solid var(--border-color);
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            box-shadow: var(--card-shadow);
            z-index: 1000;
        }

        .section {
            margin-bottom: 40px;
        }

        .section-title {
            font-size: 1.8em;
            margin-bottom: 20px;
            color: var(--text-primary);
            border-bottom: 2px solid var(--border-color);
            padding-bottom: 10px;
        }

        .card {
            background-color: var(--bg-primary);
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
            box-shadow: var(--card-shadow);
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }

        .card-title {
            font-size: 1.3em;
            margin-bottom: 10px;
        }

        .card-title a {
            color: var(--link-color);
            text-decoration: none;
        }

        .card-title a:hover {
            text-decoration: underline;
        }

        .card-meta {
            color: var(--text-secondary);
            font-size: 0.9em;
            margin-bottom: 10px;
        }

        .card-text {
            color: var(--text-primary);
            line-height: 1.6;
        }

        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            margin-right: 8px;
            background-color: var(--bg-secondary);
        }

        footer {
            text-align: center;
            padding: 20px;
            color: var(--text-secondary);
            margin-top: 40px;
        }
    </style>
</head>
<body>
    <button class="theme-toggle" onclick="toggleTheme()">🌓 Toggle Theme</button>

    <div class="container">
        <header>
            <h1>📊 Daily Report</h1>
            <p>{{ date_str }} | {{ total_items }} items</p>
        </header>

        {% for channel, items in sections.items() %}
        <div class="section">
            <h2 class="section-title">{{ channel|replace('_', ' ')|title }}</h2>

            {% for item in items %}
            <div class="card">
                <div class="card-title">
                    <a href="{{ item.url }}" target="_blank">{{ item.title }}</a>
                </div>
                <div class="card-meta">
                    <span class="badge">{{ item.source }}</span>
                    <span>{{ item.author }}</span> |
                    <span>Score: {{ "%.1f"|format(item.score) }}</span>
                </div>
                <div class="card-text">
                    {{ item.text[:300] }}{% if item.text|length > 300 %}...{% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}

        <footer>
            <p>Generated by Newsloom 📰</p>
        </footer>
    </div>

    <script>
        function toggleTheme() {
            const html = document.documentElement;
            const currentTheme = html.getAttribute('data-theme');
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
            html.setAttribute('data-theme', newTheme);
            localStorage.setItem('theme', newTheme);
        }

        // Load saved theme
        const savedTheme = localStorage.getItem('theme') || 'light';
        document.documentElement.setAttribute('data-theme', savedTheme);
    </script>
</body>
</html>"""

        # Prepare template data
        template = Template(html_template)

        # Convert items to dicts for template
        sections = {}
        for channel, items_list in by_channel.items():
            sections[channel] = [
                {
                    'title': getattr(item, 'title', 'No title'),
                    'url': getattr(item, 'url', '#'),
                    'source': getattr(item, 'source', 'unknown'),
                    'author': getattr(item, 'author', 'Unknown'),
                    'score': getattr(item, 'score', 0),
                    'text': getattr(item, 'text', ''),
                }
                for item in items_list
            ]

        html = template.render(
            date_str=date_str,
            total_items=len(items),
            sections=sections
        )

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)

        print(f"🌐 Generated HTML: {output_path}")

    def generate(self, items, date_str: str, output_dir: Path):
        """
        生成所有配置的报告格式

        Args:
            items: Item 列表 或 AI briefs 字典
            date_str: 日期字符串
            output_dir: 输出目录
        """
        print(f"\n📝 生成报告中...")

        # 判断是 Items 还是 AI briefs
        if isinstance(items, dict):
            # AI briefs 格式: {section: [briefs]}
            if 'markdown' in self.formats:
                md_path = output_dir / 'report.md'
                self.generate_markdown_from_briefs(items, date_str, md_path)

            if 'html' in self.formats:
                html_path = output_dir / 'report.html'
                self.generate_html_from_briefs(items, date_str, html_path)
        else:
            # 原始 Items
            if 'markdown' in self.formats:
                md_path = output_dir / 'report.md'
                self.generate_markdown(items, date_str, md_path)

            if 'html' in self.formats:
                html_path = output_dir / 'report.html'
                self.generate_html(items, date_str, html_path)

        # TODO: Implement card generation with Playwright (Phase 4)
        # TODO: Implement RSS feed generation (Phase 4)

        print(f"✅ 报告已生成: {output_dir}")

    def generate_markdown_from_briefs(self, briefs: Dict, date_str: str, output_path: Path):
        """从 AI briefs 生成 Markdown"""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            f"# Daily Report - {date_str}",
            "",
            f"*Generated by Newsloom AI at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
            "",
            "---",
            ""
        ]

        # Table of contents
        lines.append("## Table of Contents")
        lines.append("")
        for section in sorted(briefs.keys()):
            section_name = section.replace('_', ' ').title()
            lines.append(f"- [{section_name}](#{section.lower()})")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Content sections
        for section in sorted(briefs.keys()):
            section_briefs = briefs[section]
            section_name = section.replace('_', ' ').title()

            lines.append(f"## {section_name}")
            lines.append("")
            lines.append(f"*{len(section_briefs)} items*")
            lines.append("")

            for i, brief in enumerate(section_briefs, 1):
                headline = brief.get('headline', 'No headline')
                detail = brief.get('detail', '')
                url = brief.get('url', '#')
                source = brief.get('source', 'unknown')

                lines.append(f"### {i}. [{headline}]({url})")
                lines.append("")
                lines.append(f"**来源:** {source}")
                lines.append("")
                if detail:
                    lines.append(f"{detail}")
                    lines.append("")
                lines.append("---")
                lines.append("")

        # Footer
        lines.append("")
        lines.append("---")
        lines.append("")
        lines.append("*Generated by Newsloom 📰*")

        # Write file
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))

        print(f"📄 Markdown 已生成: {output_path}")

    def generate_html_from_briefs(self, briefs: Dict, date_str: str, output_path: Path):
        """从 AI briefs 生成 HTML"""
        output_path.parent.mkdir(parents=True, exist_ok=True)

        # 使用相同的 HTML 模板，但传入 briefs 数据
        html_template = self._get_html_template()
        template = Template(html_template)

        # 准备数据
        sections = {}
        total_items = 0
        for section, section_briefs in briefs.items():
            sections[section] = [
                {
                    'title': brief.get('headline', 'No title'),
                    'url': brief.get('url', '#'),
                    'source': brief.get('source', 'unknown'),
                    'author': '',
                    'score': 0,
                    'text': brief.get('detail', ''),
                }
                for brief in section_briefs
            ]
            total_items += len(section_briefs)

        html = template.render(
            date_str=date_str,
            total_items=total_items,
            sections=sections
        )

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html)

        print(f"🌐 HTML 已生成: {output_path}")

    def _get_html_template(self) -> str:
        """获取 HTML 模板"""
        return """<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Daily Report - {{ date_str }}</title>
    <style>
        :root {
            --bg-primary: #ffffff;
            --bg-secondary: #f5f5f5;
            --text-primary: #333333;
            --text-secondary: #666666;
            --border-color: #e0e0e0;
            --link-color: #0066cc;
            --card-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }

        [data-theme="dark"] {
            --bg-primary: #1a1a1a;
            --bg-secondary: #2d2d2d;
            --text-primary: #e0e0e0;
            --text-secondary: #a0a0a0;
            --border-color: #404040;
            --link-color: #66b3ff;
            --card-shadow: 0 2px 8px rgba(0,0,0,0.5);
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "PingFang SC", "Microsoft YaHei", sans-serif;
            line-height: 1.6;
            background-color: var(--bg-secondary);
            color: var(--text-primary);
            transition: background-color 0.3s, color 0.3s;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }

        header {
            background-color: var(--bg-primary);
            padding: 30px 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            box-shadow: var(--card-shadow);
        }

        h1 {
            font-size: 2.5em;
            margin-bottom: 10px;
        }

        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            background-color: var(--bg-primary);
            border: 1px solid var(--border-color);
            padding: 10px 20px;
            border-radius: 20px;
            cursor: pointer;
            box-shadow: var(--card-shadow);
            z-index: 1000;
        }

        .section {
            margin-bottom: 40px;
        }

        .section-title {
            font-size: 1.8em;
            margin-bottom: 20px;
            color: var(--text-primary);
            border-bottom: 2px solid var(--border-color);
            padding-bottom: 10px;
        }

        .card {
            background-color: var(--bg-primary);
            border-radius: 8px;
            padding: 20px;
            margin-bottom: 20px;
            box-shadow: var(--card-shadow);
            transition: transform 0.2s;
        }

        .card:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0,0,0,0.15);
        }

        .card-title {
            font-size: 1.3em;
            margin-bottom: 10px;
        }

        .card-title a {
            color: var(--link-color);
            text-decoration: none;
        }

        .card-title a:hover {
            text-decoration: underline;
        }

        .card-meta {
            color: var(--text-secondary);
            font-size: 0.9em;
            margin-bottom: 10px;
        }

        .card-text {
            color: var(--text-primary);
            line-height: 1.6;
        }

        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.8em;
            margin-right: 8px;
            background-color: var(--bg-secondary);
        }

        footer {
            text-align: center;
            padding: 20px;
            color: var(--text-secondary);
            margin-top: 40px;
        }
    </style>
</head>
<body>
    <button class="theme-toggle" onclick="toggleTheme()">🌓 切换主题</button>

    <div class="container">
        <header>
            <h1>📊 Daily Report</h1>
            <p>{{ date_str }} | {{ total_items }} items | Powered by Newsloom AI</p>
        </header>

        {% for section, items in sections.items() %}
        <div class="section">
            <h2 class="section-title">{{ section|replace('_', ' ')|title }}</h2>

            {% for item in items %}
            <div class="card">
                <div class="card-title">
                    <a href="{{ item.url }}" target="_blank">{{ item.title }}</a>
                </div>
                {% if item.source %}
                <div class="card-meta">
                    <span class="badge">{{ item.source }}</span>
                </div>
                {% endif %}
                <div class="card-text">
                    {{ item.text }}
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}

        <footer>
            <p>Generated by Newsloom 📰</p>
        </footer>
    </div>

    <script>
        function toggleTheme() {
            const html = document.documentElement;
            const currentTheme = html.getAttribute('data-theme');
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';
            html.setAttribute('data-theme', newTheme);
            localStorage.setItem('theme', newTheme);
        }

        // Load saved theme
        const savedTheme = localStorage.getItem('theme') || 'light';
        document.documentElement.setAttribute('data-theme', savedTheme);
    </script>
</body>
</html>"""
