name: "Harvard Crimson"
description: "Academic authority design inspired by Harvard University. Classic white background with Crimson red accents, Georgia serif typography for scholarly elegance."
version: "1.0.0"
author: "Newsloom Templates"
theme: "light"
features:
  - "Crimson red (#A51C30) accent color"
  - "Georgia serif headings for academic authority"
  - "Clean white background"
  - "Elegant quote boxes with gray backgrounds"
  - "Professional academic layout"
  - "PDF/print optimized"
  - "CJK font support"
  - "Priority indicators (🔴/🟡/🟢)"