name: "bauhaus"
description: "包豪斯风格 — 三原色几何设计，功能即美学，现代主义极简"
version: "1.0.0"
author: "Newsloom Template Factory"
theme: "light"
features:
  - "三原色设计 红蓝黄"
  - "几何方块排版"
  - "Futura 风格字体"
  - "功能即美学"
  - "现代主义极简"
  - "A4 PDF 优化"