name: "Nordic Minimal"
description: "Scandinavian-inspired minimal design with warm natural aesthetics. Soft warm white background with gentle sage green accents, abundant whitespace for calm readability."
version: "1.0.0"
author: "Newsloom Templates"
theme: "light"
features:
  - "Sage green (#5B7065) natural accents"
  - "Warm white (#FAF9F6) soothing background"
  - "Abundant whitespace for tranquility"
  - "Soft rounded corners and gentle styling"
  - "Nordic minimalist aesthetic"
  - "PDF/print optimized"
  - "CJK font support"
  - "Priority indicators (🔴/🟡/🟢)"