name: "WSJ Classic"
description: "Wall Street Journal inspired classic newspaper design with serif typography, two-column layout, and timeless elegance. Warm ivory background with traditional newspaper aesthetics."
version: "1.0.0"
author: "Newsloom"
theme: "light"
features:
  - "Classic newspaper masthead with double-line borders"
  - "Serif typography (Georgia, Playfair Display)"
  - "Two-column CSS layout for article briefs"
  - "Drop-cap first letter in executive summary"
  - "Warm ivory background (#FFFEF5)"
  - "WSJ blue (#0080C6) accent color"
  - "Traditional horizontal rules between sections"
  - "Elegant, timeless newspaper design"
