name: "midnight-gold"
description: "午夜金色 — 深海蓝底，琥珀金点缀，Premium 高端设计"
version: "1.0.0"
author: "Newsloom Template Factory"
theme: "dark"
features:
  - "琥珀金色渐变分隔线"
  - "优雅衬线体标题"
  - "Premium 高端视觉感"
  - "深海蓝 #0B0F19 底色"
  - "琥珀金 #F59E0B 点缀"
  - "A4 PDF 优化"