name: "Ink Wash (水墨风)"
description: "Chinese traditional aesthetics with rice paper background, vermillion seal accents, and ink wash gradients. Features Song typeface and traditional Chinese design language."
version: "1.0.0"
author: "Newsloom"
theme: "light"
features:
  - "Rice paper texture background (#F5F0E8)"
  - "Vermillion red seal stamps (朱印)"
  - "Chinese quotation marks「」in executive summary"
  - "Ink wash gradient separators"
  - "Chinese priority labels (必读/推荐/了解)"
  - "Noto Serif SC / Song typeface for headers"
  - "Traditional Chinese aesthetic elements"
  - "Beautiful CJK typography spacing"
