name: "Notion Clean"
description: "Ultra-minimal Notion-inspired design with generous spacing, system fonts, and distraction-free content-first layout. Features table of contents and checkbox-style priority indicators."
version: "1.0.0"
author: "Newsloom"
theme: "light"
features:
  - "Notion-style clean aesthetic"
  - "System font stack (-apple-system, Segoe UI)"
  - "Generous line-height (1.8) and spacing"
  - "Table of contents with dotted leaders"
  - "Checkbox priority indicators (☐/☑/🔲)"
  - "Callout-style executive summary"
  - "Clean white background"
  - "Content-first minimal design"
